// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBtU6U4BCmxi3gWHGwPS7ABeOkZsnf6Klc",
    appId: "1:293471316653:web:43a8d6669a889536bef424",
    messagingSenderId: "293471316653",
    projectId: "ace-firebase-9129a",
    authDomain: "ace-firebase-9129a.firebaseapp.com",
    storageBucket: "ace-firebase-9129a.firebasestorage.app",
    measurementId: "G-DR35R14XJK",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCvaZROsSgVzkZcolzw3I7RiMBxAUpcsE',
    appId: '1:293471316653:android:aa34c913b289ddc8bef424',
    messagingSenderId: '293471316653',
    projectId: 'ace-firebase-9129a',
    storageBucket: 'ace-firebase-9129a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBtU6U4BCmxi3gWHGwPS7ABeOkZsnf6Klc",
    appId: "1:293471316653:web:92e8771b806485bebef424",
    messagingSenderId: "293471316653",
    projectId: "ace-firebase-9129a",
    authDomain: "ace-firebase-9129a.firebaseapp.com",
    storageBucket: "ace-firebase-9129a.firebasestorage.app",
    measurementId: "G-LTD2HX5JBP",
  );
}
